# Pin npm packages by running ./bin/importmap

pin "application"
pin "@hotwired/turbo-rails", to: "turbo.min.js"
pin "@hotwired/stimulus", to: "stimulus.min.js"
pin "@hotwired/stimulus-loading", to: "stimulus-loading.js"
pin_all_from "app/javascript/controllers", under: "controllers"
pin "@rails/actioncable", to: "actioncable.esm.js"
pin_all_from "app/javascript/channels", under: "channels"
pin "handsontable", to: "https://ga.jspm.io/npm:handsontable@14.2.0/index.mjs"
pin "@handsontable/pikaday", to: "https://ga.jspm.io/npm:@handsontable/pikaday@1.0.0/pikaday.mjs"
pin "core-js/modules/", to: "https://ga.jspm.io/npm:core-js@3.36.1/modules/"
pin "dompurify", to: "https://ga.jspm.io/npm:dompurify@2.4.9/dist/purify.js"
pin "moment", to: "https://ga.jspm.io/npm:moment@2.29.4/moment.js"
pin "numbro", to: "https://ga.jspm.io/npm:numbro@2.1.2/dist/numbro.min.js"
